### ISSUE TITLE
Foo example on website crashes with java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator

### ISSUE THREAD

**Issue by olafurpg** [lihaoyi/mill#132]
I was following http://www.lihaoyi.com/mill/page/configuring-mill.html#adding-ivy-dependencies and `mill foo.run` in the following build
```scala
// build.sc
import mill._
import mill.scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.12.4"
  def ivyDeps = Agg(
    ivy"com.lihaoyi::pprint:0.5.3",
  )
}
// foo/src/Main.scala
package a

object Main extends App {
  pprint.log("Hello world!")
}
```

crashes with 
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
	at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
	at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at fansi.ColorCategory.<init>(Fansi.scala:850)
	at fansi.Color$.<init>(Fansi.scala:717)
	at fansi.Color$.<clinit>(Fansi.scala)
	at pprint.PPrinter$.$lessinit$greater$default$4(PPrinter.scala:18)
	at pprint.package$.<init>(package.scala:7)
	at pprint.package$.<clinit>(package.scala)
	at a.Main$.delayedEndpoint$a$Main$1(Main.scala:4)
	at a.Main$delayedInit$body.apply(Main.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at a.Main$.main(Main.scala:3)
	at a.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
1 targets failed
foo.run ammonite.ops.InteractiveShelloutException
    ammonite.ops.Shellout$.executeInteractive(Shellout.scala:56)
    ammonite.ops.Shellout$.$anonfun$$percent$1(Shellout.scala:14)
    ammonite.ops.Shellout$.$anonfun$$percent$1$adapted(Shellout.scala:14)
    ammonite.ops.Command.applyDynamic(Shellout.scala:118)
    mill.modules.Jvm$.interactiveSubprocess(Jvm.scala:37)
    mill.scalalib.ScalaModule.$anonfun$run$2(ScalaModule.scala:222)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
```

Adding a library that is not on the default ammonite classpath seems to work fine, I can only reproduce the error with pprint/fansi.

Congrats on the release! Docs look great, IntelliJ import just worked,  --watch is amazing.

**Comment by lihaoyi** [comment]
Bah looks like i'm missing a `scala-reflect` dependency...

**Comment by lihaoyi** [comment]
This should get it working
```scala
lihaoyi mill$ cat ~/test/build.sc
// build.sc
import mill._
import mill.scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.12.4"
  def ivyDeps = Agg(
    ivy"com.lihaoyi::pprint:0.5.3",
    ivy"org.scala-lang:scala-reflect:${scalaVersion()}"
  )
}
```

**Comment by olafurpg** [comment]
Whoops, adding scala-reflect indeed fixed the problem. Should pprint bring in scala-reflect transively? pprint depends on scala-reflect in the "provided" scope http://repo1.maven.org/maven2/com/lihaoyi/pprint_2.12/0.5.3/pprint_2.12-0.5.3.pom
