### ISSUE TITLE
Failed to construct terminal; falling back to unsupported

### ISSUE THREAD

**Issue by aeons** [lihaoyi/mill#139]
I get the following stack trace for most (all?) `mill` commands, but it seems to only show up the first time I run them. It doesn't seem to affect the actual command.

This is running in Arch using `alacritty` as the terminal.

```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at sbt.internal.util.ConsoleAppender$.ansiSupported(ConsoleAppender.scala:245)
        at sbt.internal.util.ConsoleAppender$.<init>(ConsoleAppender.scala:107)
        at sbt.internal.util.ConsoleAppender$.<clinit>(ConsoleAppender.scala)
        at sbt.internal.util.MainAppender$.defaultScreen(MainLogging.scala:61)
        at mill.scalaworker.ScalaWorker.compileScala(ScalaWorker.scala:168)
        at mill.scalalib.ScalaModule.$anonfun$compile$2(ScalaModule.scala:130)
        at mill.define.ApplyerGenerated.$anonfun$zipMap$9(ApplicativeGenerated.scala:21)
        at mill.define.Task$MappedDest.evaluate(Task.scala:358)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$14(Evaluator.scala:297)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withErr(Console.scala:192)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:297)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withOut(Console.scala:163)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$9(Evaluator.scala:296)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$9$adapted(Evaluator.scala:254)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:254)
        at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:179)
        at mill.eval.Evaluator.$anonfun$evaluate$2(Evaluator.scala:86)
        at mill.eval.Evaluator.$anonfun$evaluate$2$adapted(Evaluator.scala:83)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at mill.eval.Evaluator.evaluate(Evaluator.scala:83)
        at mill.main.RunScript$.evaluate(RunScript.scala:216)
        at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:202)
        at scala.util.Either.map(Either.scala:350)
        at mill.main.RunScript$.evaluateTasks(RunScript.scala:201)
        at mill.main.RunScript$.$anonfun$runScript$3(RunScript.scala:57)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at mill.main.RunScript$.runScript(RunScript.scala:56)
        at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:46)
        at ammonite.MainRunner.watchLoop(Main.scala:350)
        at mill.main.MainRunner.runScript(MainRunner.scala:34)
        at mill.Main$.main(Main.scala:66)
        at mill.Main.main(Main.scala)
```

**Comment by aeons** [comment]
It only showed up the first time on `mill todo.run`, but it's every time when doing `mill todo.test`.

This is the project: https://github.com/aeons/todo-backend-typelevel/tree/mill

**Comment by lihaoyi** [comment]
I suspect it has something to do with arch/alacritty. Not familiar enough with those to say what it is :/

**Comment by DavidGregory084** [comment]
@lihaoyi I have seen this issue before in SBT [here](https://github.com/sbt/sbt/issues/3240), I believe this was fixed by upgrading JLine to 2.14.4?

**Comment by lihaoyi** [comment]
@aeons maybe try forcing jline to that version in build.sbt/build.sc and seeing if it fixes things?

**Comment by aeons** [comment]
Not sure how to do that? I tried adding jline 2.14.5 to ivyDeps, but that didn't change anything. However the `TERM=xterm-color` env var from the linked SBT issues fixed it, so I assume it's the same issue.

**Comment by lihaoyi** [comment]
Cool I'll close this for now then, if there's some change in Mill that would help feel free to send a PR

**Comment by lihaoyi** [comment]
@rockjam since you're getting this, want to try forcing the jline upgrade someone suggested? There's already a PR open for Ammonite repo but we can just bump the version in Mill first to see if it solves the problem

**Comment by rockjam** [comment]
@lihaoyi yes, I'll do it

**Comment by rom1dep** [comment]
74255b7 does fix the issue for me. GTG.

**Comment by rockjam** [comment]
Good

**Comment by jjotta158** [comment]
mann add this command in your ~/.zshrc:
export TERM=xterm-color

it works with me
