### ISSUE TITLE
RuntimeException: Nonzero exit value: 1 loop

### ISSUE THREAD

**Issue by francisdb** [lihaoyi/mill#171]
mill `0.1.3`
macOS 10.13.3 (17D47)

started with docs on http://www.lihaoyi.com/mill/
added the example build.sc to an existing sbt project folder

I get alternating results when running just `mill`

```
mill
Loading...
@ Bye!
```

```
mill
Loading...
java.lang.RuntimeException: Nonzero exit value: 1
  scala.sys.package$.error(package.scala:27)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:134)
  scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:104)
  ammonite.terminal.TTY$.stty(Utils.scala:118)
  ammonite.terminal.TTY$.init(Utils.scala:104)
  ammonite.terminal.Terminal$.x$1$lzycompute$1(Terminal.scala:41)
  ammonite.terminal.Terminal$.x$1$1(Terminal.scala:41)
  ammonite.terminal.Terminal$.initialConfig$lzycompute$1(Terminal.scala:41)
  ammonite.terminal.Terminal$.initialConfig$1(Terminal.scala:41)
  ammonite.terminal.Terminal$.readLine(Terminal.scala:52)
  ammonite.repl.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:118)
  ammonite.repl.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
  ammonite.repl.Repl.$anonfun$action$1(Repl.scala:157)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.repl.Repl.action(Repl.scala:141)
  ammonite.repl.Repl.loop$1(Repl.scala:181)
  ammonite.repl.Repl.run(Repl.scala:197)
  ammonite.Main.$anonfun$run$2(Main.scala:201)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.Main.run(Main.scala:188)
  mill.Main$.$anonfun$main0$4(Main.scala:166)
  ammonite.MainRunner.watchLoop(Main.scala:351)
  mill.Main$.main0(Main.scala:166)
  mill.ServerMain$.main0(Main.scala:77)
  mill.clientserver.Server.$anonfun$handleRun$1(Server.scala:81)
  java.lang.Thread.run(Thread.java:748)


java.lang.RuntimeException: Nonzero exit value: 1
...

loops forever
^c
```

```
mill
Loading...
@ Bye!
```

**Comment by rockjam** [comment]
Try `mill -i` to dive inside build REPL, or run `mill module.target` to run a specific task in batch mode. Or is it mainly about error message you got?

**Comment by francisdb** [comment]
Yes, I got started by now, but I expect that endless loop to not be on purpose :-)

**Comment by AlexITC** [comment]
I have been getting another error which might be due to the same problem, the current workaround seems to be using the `-i` option:

```
Exception in thread "Thread-1" java.io.IOException: com.sun.jna.LastErrorException: [32] Broken pipe
    at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:187)
    at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.write(UnixDomainSocket.java:171)
    at mill.clientserver.ClientInputPumper.run(ClientServer.scala:114)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.jna.LastErrorException: [32] Broken pipe
    at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.write(Native Method)
    at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:180)
    ... 3 more
```

**Comment by lihaoyi** [comment]
Yeah the build REPL should raise an error and ask you to `-i` as well, rather than just hanging

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/mill/commit/02e64b943b90387993f8f7bd7e3cd265ee569d27
