### ISSUE TITLE
Mill Docker image

### ISSUE THREAD

**Issue by nightscape** [lihaoyi/mill#186]
Hi all,
I've created a docker base image for mill so that it's easier to start a dockerized project with it:
https://hub.docker.com/r/nightscape/scala-mill/
I would happily contribute this as a PR to this repo.
IMO it makes sense to have an official Docker build to reduce fragmentation.

Two additional questions:
I tried to run Mill once during the Docker build so that it precompiles all the predefs etc.
Unfortunately that [failed on Docker Hub](https://hub.docker.com/r/nightscape/scala-mill/builds/bv5v6hgxxnup92but4ouv4e/) (but not locally) because of a
```
Exception in thread "main" java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory
	at org.scalasbt.ipcsocket.UnixDomainSocket.<init>(UnixDomainSocket.java:62)
	at mill.clientserver.Client.$anonfun$run$1(Client.scala:43)
	at mill.clientserver.ClientServer$.retry(ClientServer.scala:40)
	at mill.clientserver.Client.run(Client.scala:43)
	at mill.ClientMain$.$anonfun$main$1(Main.scala:60)
	at mill.ClientMain$.$anonfun$main$1$adapted(Main.scala:51)
	at mill.clientserver.Client$.WithLock(Client.scala:20)
	at mill.ClientMain$.main(Main.scala:51)
	at mill.ClientMain.main(Main.scala)
```
Do you have any idea how one could work around that?

It also seems that Mill still sometimes recompiles the predef files although it shouldn't be necessary.
I saw https://github.com/lihaoyi/Ammonite/issues/542 but that should be solved, right?

**Comment by lihaoyi** [comment]
@nightscape could you try using `mill -i` for things you run in docker/docker-hub? That would avoid the client-server setup, which is ok because command-latency on docker-hub doesn't matter, and removes one source of flakiness

**Comment by nightscape** [comment]
The `-i` flag helped. Any opinions on creating a PR and having an official `lihaoyi/scala-mill` Docker base image?
Also, is it a known problem about stuff recompiling although it shouldn't be necessary?
I only found closed issues in the Ammonite repo.
