### ISSUE TITLE
"Invalid signature file digest for Manifest main attributes" when running assembled jar

### ISSUE THREAD

**Issue by gabro** [lihaoyi/mill#231]
I've tried running `assembly` on a project and when I try to run the produced jar with:

```
java -cp out.jar myproject.Boot
```

I get

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
        at java.util.jar.JarVerifier.update(JarVerifier.java:228)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
        at java.util.jar.JarFile.getInputStream(JarFile.java:450)
        at sun.misc.JarIndex.getJarIndex(JarIndex.java:137)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:839)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:831)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:830)
        at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:803)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:530)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:520)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:519)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:492)
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:457)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:211)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

I googled a bit and the reason seems to be that I have at least one dependency with a signed JAR. However, the JAR produced by sbt-assembly doesn't raise the same error, so I'm wondering whether Mill could handle this case.

I'm also willing to contribute a patch, if someone can point me in the right direction :)

**Comment by gabro** [comment]
Ah, I found where sbt-assembly explicitly manages it:

https://github.com/sbt/sbt-assembly/blob/2ff7635afc27a7d2255167dedf1d56a58fb8d651/src/main/scala/sbtassembly/MergeStrategy.scala#L137

The solution seems to exclude the signature files while merging
