### ISSUE TITLE
java.lang.SecurityException: Prohibited package name on java 9

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#251]
On java 9 there is a SecurityException occurs in tests. For instance on play-json build(in tests): 

```
play.api.libs.json.JsResultSpec *** ABORTED ***
  java.lang.ExceptionInInitializerError:
  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:581)
  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
  at play.api.libs.json.jackson.JacksonJson$.<init>(JacksonJson.scala:224)
  at play.api.libs.json.jackson.JacksonJson$.<clinit>(JacksonJson.scala)
  at play.api.libs.json.StaticBinding$.generateFromJsValue(StaticBinding.scala:23)
  at play.api.libs.json.Json$.stringify(Json.scala:178)
  at play.api.libs.json.JsResult$Exception.<init>(JsResult.scala:250)
  at play.api.libs.json.JsResult$.$anonfun$toTry$default$2$1(JsResult.scala:268)
  at play.api.libs.json.JsResult$.toTry(JsResult.scala:269)
  at play.api.libs.json.JsResultSpec.$anonfun$new$5(JsResultSpec.scala:32)
  ...
  Cause: java.lang.SecurityException: Prohibited package name: java.sql
  at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:889)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
  at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
  at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
  at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
  at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
  at java.base/java.security.AccessController.doPrivileged(Native Method)
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
  ...
java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:581)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
	at play.api.libs.json.jackson.JacksonJson$.<init>(JacksonJson.scala:224)
	at play.api.libs.json.jackson.JacksonJson$.<clinit>(JacksonJson.scala)
	at play.api.libs.json.StaticBinding$.generateFromJsValue(StaticBinding.scala:23)
	at play.api.libs.json.Json$.stringify(Json.scala:178)
	at play.api.libs.json.JsResult$Exception.<init>(JsResult.scala:250)
	at play.api.libs.json.JsResult$.$anonfun$toTry$default$2$1(JsResult.scala:268)
	at play.api.libs.json.JsResult$.toTry(JsResult.scala:269)
	at play.api.libs.json.JsResultSpec.$anonfun$new$5(JsResultSpec.scala:32)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
	at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
	at org.scalatest.WordSpec.run(WordSpec.scala:1881)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
	at mill.scalaworker.ScalaWorker.$anonfun$runTests$5(ScalaWorker.scala:285)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at mill.scalaworker.ScalaWorker.$anonfun$runTests$2(ScalaWorker.scala:279)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mill.scalaworker.ScalaWorker.$anonfun$runTests$1(ScalaWorker.scala:269)
	at mill.modules.Jvm$.inprocess(Jvm.scala:123)
	at mill.scalaworker.ScalaWorker.runTests(ScalaWorker.scala:264)
	at mill.scalaworker.ScalaWorker$.main(ScalaWorker.scala:70)
	at mill.scalaworker.ScalaWorker.main(ScalaWorker.scala)
Caused by: java.lang.SecurityException: Prohibited package name: java.sql
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:889)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.fasterxml.jackson.databind.ser.std.StdJdkSerializers.all(StdJdkSerializers.java:55)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.<clinit>(BasicSerializerFactory.java:93)
	... 65 more
```

Details are here: https://travis-ci.org/rockjam/play-json/jobs/356007000#L869

Same build works fine on java 8

**Comment by rockjam** [comment]
Got more details. It happens only in tests. Will check class loading related things in tests

**Comment by rockjam** [comment]
Found it: https://stackoverflow.com/a/46494286 

> The changes in JDK 9 may impact code that creates class loaders with null (that is, the bootstrap class loader) as the parent class loader and assumes that all platform classes are visible to the parent. Such code may need to be changed to use the platform class loader as the parent (see ClassLoader.getPlatformClassLoader).

Will update PR with this knowledge
