### ISSUE TITLE
Unable to run a single test suite in ScalaTest

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#344]
Currently you can't run single test suite, or group of test suites from scalatest. Tried:
```
mill module.test com.example.TestSuite
mill module.test -s com.example.TestSuite
mill module.test -m com.example
mill module.test -q TestSuite
```

None of that worked.

`org.scalatest.tools.Framework`'s documentation says:

```
Integration in sbt 0.13 supports same argument format as Runner, except the following arguments:
-s -- suite is not supported because sbt's test-only serves the similar purpose
-q is not supported because test discovery should be handled by sbt, and sbt's test-only or test filter serves the similar purpose
```

**Comment by narma** [comment]
Yeah, I can provide stacktraces with my tries:

```mill scheduler.test -m com.elama.bidmanager.scheduler.ng
[55/55] scheduler.test.test 
java.lang.IllegalArgumentException: -K needs to be followed by a host name and port number
java.lang.IllegalArgumentException: -K needs to be followed by a host name and port number
	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:744)
	at org.scalatest.tools.Framework.runner(Framework.scala:1006)
	at mill.scalalib.Lib$.$anonfun$runTests$2(Lib.scala:216)
	at mill.scalalib.Lib$.$anonfun$runTests$2$adapted(Lib.scala:215)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mill.scalalib.Lib$.$anonfun$runTests$1(Lib.scala:215)
	at mill.modules.Jvm$.inprocess(Jvm.scala:120)
	at mill.scalalib.Lib$.runTests(Lib.scala:210)
	at mill.scalalib.worker.ScalaWorker$.main(ScalaWorker.scala:61)
	at mill.scalalib.worker.ScalaWorker.main(ScalaWorker.scala)```


```mill scheduler.test -s com.elama.bidmanager.scheduler.ng.NgConversionBridgeSpec
[55/55] scheduler.test.test 
java.lang.IllegalArgumentException: Specifying a suite (-s <suite>) or nested suite (-i <nested suite>) is not supported when running ScalaTest from sbt; Please use sbt's test-only instead.
java.lang.IllegalArgumentException: Specifying a suite (-s <suite>) or nested suite (-i <nested suite>) is not supported when running ScalaTest from sbt; Please use sbt's test-only instead.
	at org.scalatest.tools.Framework.parseSuiteArgs(Framework.scala:902)
	at org.scalatest.tools.Framework.runner(Framework.scala:990)
	at mill.scalalib.Lib$.$anonfun$runTests$2(Lib.scala:216)
	at mill.scalalib.Lib$.$anonfun$runTests$2$adapted(Lib.scala:215)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mill.scalalib.Lib$.$anonfun$runTests$1(Lib.scala:215)
	at mill.modules.Jvm$.inprocess(Jvm.scala:120)
	at mill.scalalib.Lib$.runTests(Lib.scala:210)
	at mill.scalalib.worker.ScalaWorker$.main(ScalaWorker.scala:61)
	at mill.scalalib.worker.ScalaWorker.main(ScalaWorker.scala)
1 targets failed```

**Comment by lihaoyi** [comment]
> -s -- suite is not supported because sbt's test-only serves the similar purpose
> -q is not supported because test discovery should be handled by sbt, and sbt's test-only or test filter serves the similar purpose

Maybe we can open an issue with ScalaTest asking that they turn these back on? I spent some time in the past trying to dig through the argument parsing code to see if I could send a PR but couldn't make head or tail of it

**Comment by Baccata** [comment]
I'm using Specs2 and could not find an argument accepted by the runner that would support filtering sources. The documentation around that feature seems to assume sbt usage, and the sources gave me nothing. I tried to dig up what sort of mechanism sbt uses in the testOnly task, but gave up due to lack of time. 

If there is some sbt machinery that allows for filtering tests regardless of the test framework, it'd be great to have it in mill too.

**Comment by rockjam** [comment]
> Maybe we can open an issue with ScalaTest asking that they turn these back on

Sounds good, will do

**Comment by vic** [comment]
@antonkulaga how are you running a single ScalaTest ?

**Comment by davoclavo** [comment]
This is not an ideal solution, but a current workaround is to run the specs via the repl. e.g.

```
mill -i your_module.repl
```

In the repl:
```
(new com.your_package.YourSpecificSpec).execute()
```

**Comment by tekacs** [comment]
For Specs2, you may want to simply define a custom task like my `specs2` task below:

```scala
  object test extends Tests {
    override def ivyDeps = Agg(
      ivy"org.specs2::specs2-core:4.3.4",
      ivy"org.tpolecat::doobie-specs2:${Versions.doobie}",
    )
    def testFrameworks = Seq(
      "org.specs2.runner.Specs2Framework"
    )
    def testOne(args: String*) = T.command {
      super.runMain("specs2.run", args: _*)
    }
  }
```

You can then use it as follows:

```sh
mill --watch lib.test.testOne my.packaged.Test
```

You could also define another task for `org.specs2.runner.files`, which would let you run tests for all of your `*Spec` tests.

In both cases, you can use the command line arguments from here:

https://etorreborre.github.io/specs2/guide/SPECS2-2.4.17/org.specs2.guide.Runners.html#Command+line

**Comment by martinffx** [comment]
@tekacs solution worked for me with scalatest:

```  
  object test extends Tests {
    def ivyDeps = Agg(
      ivy"org.scalatest::scalatest::3.0.5"
    )
    def testFrameworks = Seq("org.scalatest.tools.Framework")

    def testOne(args: String*) = T.command {
      super.runMain("org.scalatest.run", args: _*)
    }
  }
```

**Comment by darcy-shen** [comment]
For mill 0.9.9, here is a sample usage on https://github.com/eto-ai/spark-video:

```
bin/mill 'video[2.12].test.testOnly' org.apache.spark.sql.rikai.expressions.MLImageTest
```

But it is not documented.
