### ISSUE TITLE
Class loading error: running `mdoc` task causes `MissingRequirementError` exception

### ISSUE THREAD

**Issue by hmf** [lihaoyi/mill#658]
I am trying to execute a task that parsers Markdown using [mdoc](https://github.com/scalameta/mdoc). I am using the `mdoc` code example found [here](https://scalameta.org/mdoc/docs/installation.html#library). When I execute this task (see [source code](https://gitlab.com/hmf/srllab/blob/master/build.sc#L111)) so:

```
 ./mill -i sdk.mDoc
```
I get the *infamous* error (full stack trace provided at the end):

```
Caused by: scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
```
To make sure I am not messing up anything,  I created a standard application (see [source code](https://gitlab.com/hmf/srllab/blob/master/sdk/src/srllab/MDocTest.scala#L27)) that execute as follows:

```
./mill -i sdk.runMain srllab.MDocTest 
```
and get the correct (expected) output: 
```
[33/33] sdk.runMain 
sources = /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc
sink = /home/hmf/IdeaProjects/srllab/out/sdk/mDoc/dest
info: Compiling 1 file to /home/hmf/IdeaProjects/srllab/out/sdk/mDoc/dest
info: Compiling /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc/index.md
info: Instrumented /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc/index.md
package repl
object Session extends _root_.mdoc.internal.document.DocumentBuilder {
  def app(): _root_.scala.Unit = {val _ = App}
  object App {

$doc.startSection();
$doc.startStatement(0, 0, 0, 9);
val x = 1; $doc.binder(x, 0, 4, 0, 5)
$doc.endStatement();
$doc.startStatement(1, 0, 1, 10);
val res0 = List(x, x); $doc.binder(res0, 1, 0, 1, 10)
$doc.endStatement();
$doc.endSection();
  }
}

debug: /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc/index.md: instrumented code
package repl
object Session extends _root_.mdoc.internal.document.DocumentBuilder {
  def app(): _root_.scala.Unit = {val _ = App}
  object App {

$doc.startSection();
$doc.startStatement(0, 0, 0, 9);
val x = 1; $doc.binder(x, 0, 4, 0, 5)
$doc.endStatement();
$doc.startStatement(1, 0, 1, 10);
val res0 = List(x, x); $doc.binder(res0, 1, 0, 1, 10)
$doc.endStatement();
$doc.endSection();
  }
}

info:   done => /home/hmf/IdeaProjects/srllab/out/sdk/mDoc/dest/index.md (5,59s)
info: Compiled in 5,64s (0 errors)
```
Note that according to some suggestion in the *Internet* I have added the following to the script to no avail ([code here](https://gitlab.com/hmf/srllab/blob/master/build.sc#L16)):

```
import $ivy.`org.scala-lang:scala-library:2.12.8`
import $ivy.`org.scala-lang:scala-reflect:2.12.8`
import $ivy.`org.scala-lang:scala-compiler:2.12.8`
```

In order to further diagnose this issue I was wondering if this is an `Ammonite` issue or a `Mill` one. So a redid the `mdoc`call in an Ammonite script ([see code here](https://gitlab.com/hmf/srllab/blob/master/mdocTest.sc)). Unfortunately I could not replicate the results one way or the other - this may be because the `amm` command seems to be using `Scala 2.13`.  I do however get another error:

```
amm mdocTest.sc 
Compiling /home/hmf/IdeaProjects/srllab/mdocTest.sc
sources = /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc
sink = /home/hmf/IdeaProjects/srllab/out/sdk/mDoc/dest
java.lang.NoClassDefFoundError: scala/Serializable
  java.lang.ClassLoader.defineClass1(Native Method)
  java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  java.security.AccessController.doPrivileged(Native Method)
  java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  scala.meta.internal.io.PathIO$.workingDirectory(PathIO.scala:10)
  mdoc.MainSettings$.apply(MainSettings.scala:112)
  ammonite.$file.mdocTest$.<clinit>(mdocTest.sc:27)
java.lang.ClassNotFoundException: scala.Serializable
  java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  java.lang.ClassLoader.defineClass1(Native Method)
  java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  java.security.AccessController.doPrivileged(Native Method)
  java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  scala.meta.internal.io.PathIO$.workingDirectory(PathIO.scala:10)
  mdoc.MainSettings$.apply(MainSettings.scala:112)
  ammonite.$file.mdocTest$.<clinit>(mdocTest.sc:27)
```

So can anyone tell me if how to solve this? Maybe a possible workaround? 
I would also like to now - is that Ammonite error worth reporting as a bug i the respective repository?  

Additional information:

Mill version (from the downloaded script):
```
#!/usr/bin/env sh

# This is a wrapper script, that automatically download mill from GitHub release pages
# You can give the required mill version with MILL_VERSION env variable
# If no version is given, it falls back to the value of DEFAULT_MILL_VERSION
DEFAULT_MILL_VERSION=0.5.0
```

```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

```
uname -a
Linux gandalf 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

TIA

**Full Stack Trace:**

```
mdoc.internal.cli.FileException: /home/hmf/IdeaProjects/srllab/sdk/docs/mdoc/index.md
Caused by: scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:24)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:25)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$4(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:73)
	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:179)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:198)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:198)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:199)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:199)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1238)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1237)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1367)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1366)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1409)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1409)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1465)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1194)
	at mdoc.internal.markdown.MarkdownCompiler.compileSources(MarkdownCompiler.scala:168)
	at mdoc.internal.markdown.MarkdownCompiler.compile(MarkdownCompiler.scala:181)
	at mdoc.internal.markdown.MarkdownCompiler$.buildDocument(MarkdownCompiler.scala:44)
	at mdoc.internal.markdown.MdocPostProcessor.processScalaInputs(MdocPostProcessor.scala:136)
	at mdoc.internal.markdown.MdocPostProcessor.processDocument(MdocPostProcessor.scala:46)
	at com.vladsch.flexmark.parser.internal.PostProcessorManager.postProcess(PostProcessorManager.java:70)
	at com.vladsch.flexmark.parser.internal.PostProcessorManager.processDocument(PostProcessorManager.java:53)
	at com.vladsch.flexmark.parser.Parser.postProcess(Parser.java:389)
	at com.vladsch.flexmark.parser.Parser.parse(Parser.java:369)
	at mdoc.internal.markdown.Markdown$.toDocument(Markdown.scala:81)
	at mdoc.internal.markdown.Markdown$.toMarkdown(Markdown.scala:113)
	at mdoc.internal.cli.MainOps.handleMarkdown(MainOps.scala:64)
	at mdoc.internal.cli.MainOps.handleFile(MainOps.scala:91)
	at mdoc.internal.cli.MainOps.$anonfun$generateCompleteSite$1(MainOps.scala:130)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at mdoc.internal.cli.MainOps.generateCompleteSite(MainOps.scala:128)
	at mdoc.internal.cli.MainOps.run(MainOps.scala:149)
	at mdoc.internal.cli.MainOps$.process(MainOps.scala:234)
	at mdoc.Main$.process(Main.scala:29)
	at ammonite.$file.build$sdk$.$anonfun$mDoc$2(build.sc:121)
	at mill.define.Applicative$Applyer.$anonfun$zipMap$1(Applicative.scala:35)
	at mill.define.Task$MappedDest.evaluate(Task.scala:337)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$14(Evaluator.scala:335)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:335)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:334)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:333)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:289)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:289)
	at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:188)
	at mill.eval.Evaluator.$anonfun$evaluate$2(Evaluator.scala:69)
	at mill.eval.Evaluator.$anonfun$evaluate$2$adapted(Evaluator.scala:53)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at mill.eval.Evaluator.evaluate(Evaluator.scala:53)
	at mill.main.RunScript$.evaluate(RunScript.scala:208)
	at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:194)
	at scala.util.Either.map(Either.scala:353)
	at mill.main.RunScript$.evaluateTasks(RunScript.scala:193)
	at mill.main.RunScript$.$anonfun$runScript$4(RunScript.scala:67)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at mill.main.RunScript$.runScript(RunScript.scala:66)
	at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:90)
	at mill.main.MainRunner.watchLoop2(MainRunner.scala:55)
	at mill.main.MainRunner.runScript(MainRunner.scala:70)
	at mill.MillMain$.main0(MillMain.scala:187)
	at mill.MillMain$.main(MillMain.scala:27)
	at mill.MillMain.main(MillMain.scala)
info: Compiled in 1,11s (0 errors)
error = 1
```

**Comment by hmf** [comment]
A small update: I tested unstable `0.5.0-8-52bb78` and got the same results.

**Comment by hmf** [comment]
Seems like mdoc may be doing something funky. 

As per @lihaoyi suggestion:

> download the jar in a separate task (so it’s cached) and run os.proc(“java”, “-cp”, “...”, “mdoc.Main”).run() to launch it
you can also rely on an environmentally installed version but more reliable to have Mill download it
