### ISSUE TITLE
mill --version failed to connect to server

### ISSUE THREAD

**Issue by dwalend** [lihaoyi/mill#675]
Immediately after install (via brew) mill can't report its version. It fails with an inauspicious "java.lang.Exception: Failed to connect to server"

The raw Exception gives no clue why mill can't connect to a server. The message text doesn't say what server it was trying to connect to. (Further a build tool shouldn't have to connect to a server to come up with its version.)

Error: mill 0.5.0 already installed
1 dwalend@Davids-MacBook-Pro:~/projects > mill --version
Exception in thread "main" java.lang.Exception: Failed to connect to server
	at mill.main.client.MillClientMain.run(MillClientMain.java:170)
	at mill.main.client.MillClientMain.main0(MillClientMain.java:101)
	at mill.main.client.MillClientMain.main(MillClientMain.java:69)

**Comment by lihaoyi** [comment]
Try asking for help in the gitter channel
