### ISSUE TITLE
Parallel build failure since 0.6.2-25-6628cf

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#843]
I can reproduce an build issue with 0.6.2-25/26 and `-j` != 1. It's in https://github.com/woq-blended/blended, which is still on 0.6.2 because of mill-osgi module. I bumped mill in both to test.

`mill -j 0 -d blended.activemq.brokerstarter.__.testCached` triggers the error:

```
21:49:56 ⌁ θ66° lefou:~/work/woq/blended-mill mill-futures+* 5s 1 ± mill -j 0 -d blended.activemq.brokerstarter.__.testCached
Using explicit system properties: Map()
Compiling /home/lefou/work/woq/blended-mill/build_util.sc
Compiling /home/lefou/work/woq/blended-mill/build_deps.sc
Compiling /home/lefou/work/woq/blended-mill/build.sc
Using experimental parallel evaluator with 4 threads
[#0] [320/686] blended.activemq.brokerstarter.test[other].copiedResources 
1 targets failed
blended.activemq.brokerstarter.test[other].copiedResources java.nio.file.FileAlreadyExistsException: /home/lefou/work/woq/blended-mill/out/blended/activemq/brokerstarter/test/other/copiedResources/dest/container
    sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
    sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
    java.nio.file.Files.copy(Files.java:1274)
    os.copy$.copyOne$1(FileOps.scala:173)
    os.copy$.apply(FileOps.scala:176)
    os.copy$into$.apply(FileOps.scala:191)
    ammonite.$file.build$BlendedModule$Tests.$anonfun$copiedResources$4(build.sc:157)
    ammonite.$file.build$BlendedModule$Tests.$anonfun$copiedResources$4$adapted(build.sc:156)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
    scala.collection.AbstractIterable.foreach(Iterable.scala:921)
    ammonite.$file.build$BlendedModule$Tests.$anonfun$copiedResources$3(build.sc:156)
    ammonite.$file.build$BlendedModule$Tests.$anonfun$copiedResources$3$adapted(build.sc:153)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
    scala.collection.AbstractIterable.foreach(Iterable.scala:921)
    ammonite.$file.build$BlendedModule$Tests.$anonfun$copiedResources$2(build.sc:153)
```

It's reproducible always for me. But once I saw a somewhat different error:

```
19:26:35 ⌁ θ63° lefou:~/work/woq/blended-mill master(+4/-4)+* ± mill -j 0 blended.activemq.brokerstarter.__.testCached
Using experimental parallel evaluator with 4 threads
[#0] [347/686] blended.util.resources 
[#0] Exception in thread "MillServerActionRunner" java.nio.file.DirectoryNotEmptyException: /home/lefou/work/woq/blended-mill/out/blended/activemq/brokerstarter/test/other/copiedResources/dest
[#0]    at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
[#0]    at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[#0]    at java.nio.file.Files.delete(Files.java:1126)
[#0]    at os.remove$all$.apply(FileOps.scala:229)
[#0]    at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:318)
[#0]    at mill.eval.Evaluator.$anonfun$parallelEvaluate$2(Evaluator.scala:199)
[#0]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
[#0]    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[#0]    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[#0]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[#0]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[#0]    at java.lang.Thread.run(Thread.java:748)
[#1] [352/686] blended.mgmt.base.resources
```

Looks a bit like the `T.dest` preparation is not on sync with the actual target execution.

The failing command is copying some files and dirs into it's `T.dest` dir.

**Comment by lefou** [comment]
Looks like the command `blended.activemq.brokerstarter.test[other].copiedResources` is started two times in parallel. The old parallel evaluator made sure, we never schedule a task with the same name concurrently.

![grafik](https://user-images.githubusercontent.com/1321393/80843896-ab9ade80-8c05-11ea-9fc5-7cb428f840f9.png)

**Comment by lefou** [comment]
I can workaround this issue by replacing the command by a persistent task. Here is the blueprint.

```diff
-def copiedResources(): Command[PathRef] = T.command {
+def copiedResources: T[PathRef] = T.persistent {
      val dest = T.dest
+      os.remove.all(dest)
+      os.makeDir.all(dest)
      /* do stuff */
      PathRef(dest)
}
```

But this will most likely not fix the issue with running duplicated command in one evaluation.

E.g. the following mill command is know to pull in each `test`-command twice.

```
mill __.test
```
